### PR TITLE
Fix/usv plugin

### LINKED ISSUE #4: USVPlugin is bounded with "wind plugin"
On the contrary to what [docs says](https://github.com/tidewise/simulation-gazebo_usv/blob/a6281f69049bd3f096855db82121876bc238c10c/src/USVPlugin.cpp#L20) wind plugin is not optional.

When running a sdf that defines the USVPlugin, but does not uses wind plugin (as in [deep_trekker](https://github.com/tidewise/bundles-rov/blob/deep_trekker_simulation/models/sdf/deep_trekker/model.sdf)), rock-gazebo crashes with the error:

```console
boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::physics::Model; typename boost::detail::sp_member_access<T>::type = gazebo::physics::Model*]: Assertion `px != 0' failed.
```

The culprit seems to be calling update on the plugin even when it was not found: https://github.com/tidewise/simulation-gazebo_usv/blob/a6281f69049bd3f096855db82121876bc238c10c/src/USVPlugin.cpp#L78

Looks like a default initialized `Wind` contains some null pointers that I believe are causing the assertion error on gazebo side

### PR DESCRIPTION
**Pull request by caioaamaral**
Fix #4

### CODE REVIEW

**Review by jhonasiv — APPROVED** [review]

**Comment by jhonasiv** [comment]
I actually remember thinking about whether should I declare the wind plugin as a pointer, but I couldn't see a reason to...at least you caught it quickly,

**Comment by caioaamaral** [comment]
Should I make all pointers members unique_ptr? I personally dislike using raw pointers, but decided to keep the same style I've found.

**Comment by jhonasiv** [comment]
> Should I make all pointers members unique_ptr? I personally dislike using raw pointers, but decided to keep the same style I've found.

I agree with that. It's not a lot of work, so I dont think it's a big deal to change it.

**Comment by jhonasiv** [comment]
I'm merging this since it's a bug fix. We should discuss more about updating the raw pointer to unique_ptr

**Comment by caioaamaral** [comment]
adding a regression test for this one would be ideal so we make sure we don't get into the same mistake

**Pull request merged**
